# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issue_comment:
    types : [ created, edited ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-ssh-request-and-issue-ssh-key:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: check ssh request & generate
        env:
          ISSUE_COMMENT: ${{ toJson(github.event.comment.body) }}
        if: contains(github.event.comment.body, 'ssh')
        run : | 
          echo "$ISSUE_COMMENT - got it! generate ssh key!"
          ssh-keygen 
          echo -ne "\n"
          echo -ne "\n"
          echo -ne "\n"
      
      - name: Upload the key
        uses: actions/upload-artifact@v2
        with: 
          name: ssh-key
          path: /home/runner/.ssh/id_rsa 
          

      
